base_local_planner: "dwa_local_planner/DWAPlannerROS"
DWAPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.1
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.4
  acc_lim_theta: 1.0
  acc_lim_x: 0.5
  acc_lim_y: 0.0
  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true
