obstacle_range: 2.5
raytrace_range: 3.0
inflation_radius: 0.5
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: lidar_1, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
